version: '3.1'
networks:
  momdb_postgresql:
    external: false

services:
  db-server:
    container_name: momdb_postgresql
    image: postgres:12.7
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: momdb
    networks:
      - momdb_postgresql
    volumes:
      - db-server:/var/lib/postgresql/data
    
volumes:
  db-server:
    driver: local
 